### ISSUE TITLE
Hello, Where can i download this jar???

### ISSUE THREAD

**Issue by yu1002139909** [Open-QKD-Network/qkd-net#6]
Hello, I am a graduate student and I am working on OKD network. I downloaded your project from github, and I want to try to run it, but I encountered some difficulties, can you help me answer it, thanks, and hope to receive your reply. 	

<dependency>
				<groupId>com.uwaterloo.iqc</groupId>
				<artifactId>qnl-utils</artifactId>
				<version>0.0.1-SNAPSHOT</version>
			</dependency>

**Comment by yc1997besti** [comment]
Hello, I am a graduate student studying QKD network. I want to use your code, do some application integration, and study how to better use quantum keys. However, I encountered some difficulties. Can I generously send me some information about the detailed introduction of this open QKD network project for my learning and use! If possible, please send it to 296823555@qq.com! Hope you can reply me
